blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/ruihanglix/zoro/discussions
    about: Ask questions, share ideas, or discuss anything related to Zoro in GitHub Discussions.
